import Database
import Interation as i

def add_testing_data():
    Database.db.drop_all()
    Database.db.create_all()

    # ajout de publications
    i.ajout_publication('jules', 'INF1132', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Nami', 'INF1132', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Mehdi', 'INF1132', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('jules', 'INF1120', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Nami', 'INF1120', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Mehdi', 'INF1120', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('jules', 'INF1070', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Nami', 'INF1070', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Mehdi', 'INF1070', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('jules', 'INF1070', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Nami', 'INF1070', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Mehdi', 'INF1070', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('jules', 'INF5151', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Nami', 'INF5151', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Mehdi', 'INF5151', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('jules', 'INF5153', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Nami', 'INF5153', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    i.ajout_publication('Mehdi', 'INF5153', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut commodo turpis, sit amet porttitor nibh. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla dapibus ex non purus dapibus, sit amet ultrices orci dictum. Etiam auctor non orci tempus ultricies. Ut molestie risus massa, sit amet auctor arcu viverra in. Cras vulputate purus vitae lacus ultricies, vitae gravida enim gravida. Vestibulum risus lorem, semper non lorem condimentum, hendrerit fringilla ipsum. Duis sed tellus nec erat feugiat imperdiet. Duis vitae sem ut nulla posuere malesuada. Aliquam et lacus a orci porttitor finibus.')
    
    # ajout d'étudiants
    i.ajout_utilisateur("Jules", "xxx", "youle21@yahoo.ca")
    i.ajout_utilisateur("Mehdi", "xxx", "test@test.test")
    i.ajout_utilisateur("Nami", "xxx", "foo@foo.foo")
    i.ajout_utilisateur("Emma", "xxx", "Emma@gmail.com")
    i.ajout_utilisateur("Liam", "xxx", "Liam@gmail.com")
    i.ajout_utilisateur("Olivia", "xxx", "Olivia@gmail.com")
    i.ajout_utilisateur("Noah", "xxx", "Noah@gmail.com")
    i.ajout_utilisateur("Alice", "xxx", "Alice@gmail.com")
    i.ajout_utilisateur("william", "xxx", "william@gmail.com")
    i.ajout_utilisateur("Thomas", "xxx", "Thomas@gmail.com")
    i.ajout_utilisateur("Lea", "xxx", "Lea@gmail.com")
    i.ajout_utilisateur("Sophia", "xxx", "Sophia@gmail.com")
    i.ajout_utilisateur("Logan", "xxx", "Logan@gmail.com")
    i.ajout_utilisateur("Mia", "xxx", "Mia@gmail.com")
    i.ajout_utilisateur("Jacob", "xxx", "Jacob@gmail.com")
    i.ajout_utilisateur("Nathan", "xxx", "Nathan@gmail.com")
    i.ajout_utilisateur("Charlie", "xxx", "Charlie@gmail.com")
    i.ajout_utilisateur("Amelia", "xxx", "Amelia@gmail.com")
    i.ajout_utilisateur("Edouard", "xxx", "Edouard@gmail.com")
    
    # ajout cours
    i.ajout_cours("INF1132", "H19")
    i.ajout_cours("INF1120", "AU21")
    i.ajout_cours("INF1070", "AU21")
    i.ajout_cours("MET1110", "AU21")
    i.ajout_cours("ECO1081", "AU21")
    i.ajout_cours("INF2171", "AU21")
    i.ajout_cours("INF2020", "AU21")
    i.ajout_cours("MAT4681", "AU21")
    i.ajout_cours("INF2050", "AU21")
    i.ajout_cours("INF3271", "AU21")
    i.ajout_cours("INF3190", "AU21")
    i.ajout_cours("INF3080", "AU21")
    i.ajout_cours("INF3135", "AU21")
    i.ajout_cours("INF5151", "AU21")
    i.ajout_cours("INF3173", "AU21")
    i.ajout_cours("INF5153", "AU20")
    i.ajout_cours("INF3105", "AU21")
    i.ajout_cours("INF5130", "AU21")
    i.ajout_cours("INM5151", "AU21")
    i.ajout_cours("INF6150", "AU21")
    i.ajout_cours("INF6120", "AU21")
    i.ajout_cours("INM6000", "AU21")
    i.ajout_cours("INF4170", "AU21")

    # ajout inscription
    i.ajout_inscription( "test@test.test", "INF1132" )
    i.ajout_inscription( "test@test.test", "INF5151" )
    i.ajout_inscription( "foo@foo.foo", "INF5151" )
    i.ajout_inscription( "youle21@yahoo.ca", "INF5151" )
    i.ajout_inscription( "youle21@yahoo.ca", "INF5153" )
    i.ajout_inscription( "youle21@yahoo.ca", "INF4170" )
    i.ajout_inscription( "youle21@yahoo.ca", "INF1132" )
    i.ajout_inscription( "youle21@yahoo.ca", "INF1070" )
    i.ajout_inscription( "youle21@yahoo.ca", "INF3271" )
    i.ajout_inscription( "test@test.test", "INF1132" )

    

